ORLY/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.shortcuts import redirect

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cover/', include('cover.urls', namespace='cover')),
    url(r'^$', lambda r: redirect('cover:index')),
]

cover/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^image.png/$', views.image_generator, name='image_generator'),
]

cover/models.py
from django.db import models

# Create your models here.

cover/forms.py
from urllib.parse import urlencode
from django import forms
from .utils import COLOR_CODES

class CoverForm(forms.Form):
    COLOR_CHOICES = [(i, str(COLOR_CODES[i])) for i in range(len(COLOR_CODES))]
    
    title = forms.CharField()
    top_text = forms.CharField()
    author = forms.CharField()
    animal_code = forms.ChoiceField(choices=[(i, i) for i in range(1, 41)])
    color_code = forms.ChoiceField(choices=COLOR_CHOICES)
    guide_text = forms.CharField()
    guide_text_piacement = forms.ChoiceField(
        choices=[
            ('bottom_right', 'bottom_right'),
            ('bottom_left', 'bottom_left'),
            ('top_right', 'top_right'),
            ('top_left', 'top_left'),
         ])


    @property
    def get_params(self):
        if hasattr(self, 'cleaned_data'):
            return urlencode(self.cleaned_data)
        return None

cover/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import CoverForm
from PIL import Image, ImageDraw, ImageFont
from django.conf import settings
from .utils import COLOR_CODES

def index(request):
    if request.method == 'POST':
        form = CoverForm(request.POST, request.FILES)
        if form.is_valid():
            pass   #이미지를 생성할 데이터는 여기에 있고!!
    else:
        form = CoverForm()
    return render(request, 'cover/index.html',{
        'form':form,
    })

def image_generator(request):
    title = request.GET['title']
    top_text = request.GET['top_text']
    author = request.GET['author']
    animal_code = request.GET['animal_code']
    color_index = request.GET['color_code']
    guide_text = request.GET['guide_text']
    guide_text_piacement = request.GET['guide_text_piacement'] 

    animal_path = settings.ROOT('assets', 'animal', '{}.png'.format(animal_code))
    animal_im = Image.open(animal_path)
    animal_im = animal_im.resize((400,400))

    color = COLOR_CODES[int(color_index)]

    canvas_im = Image.new('RGB',(500, 700), 'white')
    canvas_im.paste(animal_im, (50,40)) #left/top 지정

    ttf_path = settings.ROOT('assets','fonts','NanumGothic.ttf')
    draw = ImageDraw.Draw(canvas_im)

    draw.rectangle((20, 0, 480, 10), fill = color)

    draw.rectangle((10, 400, 400, 510), fill = color)

    fnt = ImageFont.truetype(ttf_path, 70)
    draw.text((45, 430), title, font=fnt, fill=(255, 255, 255, 255))

    fnt = ImageFont.truetype(ttf_path, 20)
    draw.text((160, 15), top_text, font=fnt, fill=(0, 0, 0, 255))
    
    fnt = ImageFont.truetype(ttf_path, 25)
    draw.text((360, 655), author, font=fnt, fill=(0, 0, 0, 255))

    fnt = ImageFont.truetype(ttf_path, 30)
    draw.text((120, 500), guide_text, font=fnt, fill=(0, 0, 0, 255))

    response = HttpResponse(content_type='image/png')
    canvas_im.save(response, format='PNG')
    return response

cover/templates/cover/index.html
{% extends "cover/layout.html" %}
{% load bootstrap3 %}

{%block content%}
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                    <form action="" method="post">
                        {% csrf_token %}

                        {% bootstrap_form form %}
                        <input type="submit" value="Generate O RLY" class="btn btn-primary">
                    </form>
            </div>
            <div class="col-sm-6">
                {% if form.get_params %}
                    <img src="{% url 'cover:image_generator' %}?{{ form.get_params }}" alt="">
                {% endif %}
            </div>
        </div>
    </div>

{%endblock%}

cover/templates/cover/layout.html
{% load static %}
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Cover Generator (Powered by Django)</title>
        <link rel="stylesheet" href="{% static "bootstrap-4.1.3/css/bootstrap.min.css" %}">
        <style>
            html {
                position: relative;
                min-height: 100%;
            }
            body {
                 margin-bottom: 60px; /* Margin bottom by footer height */
            }
            .footer {
                position: absolute;
                bottom: 0;
                width: 100%;
                height: 60px; /* Set the fixed height of the footer here */
                line-height: 60px; /* Vertically center the text there */
                background-color: #f5f5f5;
            }
        </style>
    </head>
    <body>
            <nav class="navbar navbar-expand-lg navbar-light ">
                    <a class="navbar-brand" href="#" style="color:blue;">Cover Generator</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                      <span class="navbar-toggler-icon"></span>
                    </button>
                  
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                      <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="#">Link</a>
                        </li>
                        <li class="nav-item dropdown">
                          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Dropdown
                          </a>
                          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="#">Action</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Something else here</a>
                          </div>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link disabled" href="#">Disabled</a>
                        </li>
                      </ul>
                      <form class="form-inline my-2 my-lg-0">
                        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                      </form>
                    </div>
                  </nav>

        {% block content %}
        {% endblock%}

        <footer class="footer">
            <div class="container">
                <span class="text-muted">&copy; 2018.08.05 django O RLY COVER DEVELOPMENT BY SENOG-MIN</span>
            </div>
        </footer>
        <script src="{% static "code.jquery.com/jquery-3.3.1.min.js" %}"></script>
        <script src="{% static "bootstrap-4.1.3/js/bootstrap.min.js" %}"></script>
    </body>
</html>